export const NAV_TYPES = {
  INTRO: 'INTRO',
  CORE: 'CORE',
  START_UP: 'START_UP',
  MAIN: 'MAIN',
  MAIN_HOME: 'MAIN_HOME',
  TAB_BUTTOM: 'TAB_BUTTOM',

  LOGIN: 'LOGIN',
  HOME: 'HOME',
  DETAIL: 'DETAIL',
};
